import type {
  BanzukeEntry,
  Basho,
  BoutResult,
  FantasyPick,
  FantasyTeam,
  Rikishi,
} from "@fantasy-sumo/domain";

export const demoBasho: Basho = {
  id: "demo-2026-05",
  name: "Demo May Basho",
  startDate: "2026-05-10",
  endDate: "2026-05-24",
  status: "active",
  currentDay: 5,
};

export const demoRikishi: Rikishi[] = [
  {
    id: "onosato",
    shikona: "Onosato",
    heya: "Nishonoseki",
  },
  {
    id: "hoshoryu",
    shikona: "Hoshoryu",
    heya: "Tatsunami",
  },
  {
    id: "kotozakura",
    shikona: "Kotozakura",
    heya: "Sadogatake",
  },
  {
    id: "kirishima",
    shikona: "Kirishima",
    heya: "Oitekaze",
  },
  {
    id: "wakatakakage",
    shikona: "Wakatakakage",
    heya: "Arashio",
  },
  {
    id: "takayasu",
    shikona: "Takayasu",
    heya: "Tagonoura",
  },
  {
    id: "ura",
    shikona: "Ura",
    heya: "Kise",
  },
  {
    id: "tobizaru",
    shikona: "Tobizaru",
    heya: "Oitekaze",
  },
];

export const demoBanzukeEntries: BanzukeEntry[] = [
  {
    id: "demo-2026-05-onosato",
    bashoId: demoBasho.id,
    rikishiId: "onosato",
    rank: "Yokozuna",
    rankOrder: 1,
  },
  {
    id: "demo-2026-05-hoshoryu",
    bashoId: demoBasho.id,
    rikishiId: "hoshoryu",
    rank: "Yokozuna",
    rankOrder: 2,
  },
  {
    id: "demo-2026-05-kotozakura",
    bashoId: demoBasho.id,
    rikishiId: "kotozakura",
    rank: "Ozeki",
    rankOrder: 3,
  },
  {
    id: "demo-2026-05-kirishima",
    bashoId: demoBasho.id,
    rikishiId: "kirishima",
    rank: "Ozeki",
    rankOrder: 4,
  },
  {
    id: "demo-2026-05-wakatakakage",
    bashoId: demoBasho.id,
    rikishiId: "wakatakakage",
    rank: "Sekiwake",
    rankOrder: 5,
  },
  {
    id: "demo-2026-05-takayasu",
    bashoId: demoBasho.id,
    rikishiId: "takayasu",
    rank: "Komusubi",
    rankOrder: 6,
  },
  {
    id: "demo-2026-05-ura",
    bashoId: demoBasho.id,
    rikishiId: "ura",
    rank: "Maegashira #1",
    rankOrder: 7,
  },
  {
    id: "demo-2026-05-tobizaru",
    bashoId: demoBasho.id,
    rikishiId: "tobizaru",
    rank: "Maegashira #2",
    rankOrder: 8,
  },
];

export const demoFantasyTeams: FantasyTeam[] = [
  {
    id: "demo-team-yusho-hunters",
    bashoId: demoBasho.id,
    displayName: "Yusho Hunters",
    ownerName: "Demo Player A",
    createdAt: "2026-05-01T09:00:00.000Z",
  },
  {
    id: "demo-team-tachiai-titans",
    bashoId: demoBasho.id,
    displayName: "Tachiai Titans",
    ownerName: "Demo Player B",
    createdAt: "2026-05-01T09:05:00.000Z",
  },
  {
    id: "demo-team-salt-circle",
    bashoId: demoBasho.id,
    displayName: "Salt Circle",
    ownerName: "Demo Player C",
    createdAt: "2026-05-01T09:10:00.000Z",
  },
  {
    id: "demo-team-dohyo-dreamers",
    bashoId: demoBasho.id,
    displayName: "Dohyo Dreamers",
    ownerName: "Demo Player D",
    createdAt: "2026-05-01T09:15:00.000Z",
  },
];

export const demoFantasyPicks: FantasyPick[] = [
  {
    id: "demo-pick-yusho-hoshoryu",
    teamId: "demo-team-yusho-hunters",
    rikishiId: "hoshoryu",
  },
  {
    id: "demo-pick-yusho-kotozakura",
    teamId: "demo-team-yusho-hunters",
    rikishiId: "kotozakura",
  },
  {
    id: "demo-pick-tachiai-onosato",
    teamId: "demo-team-tachiai-titans",
    rikishiId: "onosato",
  },
  {
    id: "demo-pick-tachiai-kirishima",
    teamId: "demo-team-tachiai-titans",
    rikishiId: "kirishima",
  },
  {
    id: "demo-pick-salt-takayasu",
    teamId: "demo-team-salt-circle",
    rikishiId: "takayasu",
  },
  {
    id: "demo-pick-salt-ura",
    teamId: "demo-team-salt-circle",
    rikishiId: "ura",
  },
  {
    id: "demo-pick-dohyo-wakatakakage",
    teamId: "demo-team-dohyo-dreamers",
    rikishiId: "wakatakakage",
  },
  {
    id: "demo-pick-dohyo-tobizaru",
    teamId: "demo-team-dohyo-dreamers",
    rikishiId: "tobizaru",
  },
];

export const demoBoutResults: BoutResult[] = [
  {
    id: "demo-2026-05-day-1-bout-1",
    bashoId: demoBasho.id,
    day: 1,
    winnerRikishiId: "onosato",
    loserRikishiId: "hoshoryu",
    kimarite: "oshidashi",
  },
  {
    id: "demo-2026-05-day-1-bout-2",
    bashoId: demoBasho.id,
    day: 1,
    winnerRikishiId: "kotozakura",
    loserRikishiId: "kirishima",
    kimarite: "yorikiri",
  },
  {
    id: "demo-2026-05-day-1-bout-3",
    bashoId: demoBasho.id,
    day: 1,
    winnerRikishiId: "takayasu",
    loserRikishiId: "ura",
    kimarite: "hatakikomi",
  },
  {
    id: "demo-2026-05-day-1-bout-4",
    bashoId: demoBasho.id,
    day: 1,
    winnerRikishiId: "wakatakakage",
    loserRikishiId: "tobizaru",
    kimarite: "oshidashi",
  },
  {
    id: "demo-2026-05-day-2-bout-1",
    bashoId: demoBasho.id,
    day: 2,
    winnerRikishiId: "onosato",
    loserRikishiId: "kotozakura",
    kimarite: "uwatenage",
  },
  {
    id: "demo-2026-05-day-2-bout-2",
    bashoId: demoBasho.id,
    day: 2,
    winnerRikishiId: "hoshoryu",
    loserRikishiId: "kirishima",
    kimarite: "yorikiri",
  },
  {
    id: "demo-2026-05-day-2-bout-3",
    bashoId: demoBasho.id,
    day: 2,
    winnerRikishiId: "ura",
    loserRikishiId: "takayasu",
    kimarite: "okuridashi",
  },
  {
    id: "demo-2026-05-day-2-bout-4",
    bashoId: demoBasho.id,
    day: 2,
    winnerRikishiId: "tobizaru",
    loserRikishiId: "wakatakakage",
    kimarite: "hikiotoshi",
  },
  {
    id: "demo-2026-05-day-3-bout-1",
    bashoId: demoBasho.id,
    day: 3,
    winnerRikishiId: "kirishima",
    loserRikishiId: "onosato",
    kimarite: "oshidashi",
  },
  {
    id: "demo-2026-05-day-3-bout-2",
    bashoId: demoBasho.id,
    day: 3,
    winnerRikishiId: "hoshoryu",
    loserRikishiId: "kotozakura",
    kimarite: "yorikiri",
  },
  {
    id: "demo-2026-05-day-3-bout-3",
    bashoId: demoBasho.id,
    day: 3,
    winnerRikishiId: "takayasu",
    loserRikishiId: "wakatakakage",
    kimarite: "tsukiotoshi",
  },
  {
    id: "demo-2026-05-day-3-bout-4",
    bashoId: demoBasho.id,
    day: 3,
    winnerRikishiId: "ura",
    loserRikishiId: "tobizaru",
    kimarite: "katasukashi",
  },
  {
    id: "demo-2026-05-day-4-bout-1",
    bashoId: demoBasho.id,
    day: 4,
    winnerRikishiId: "onosato",
    loserRikishiId: "ura",
    kimarite: "oshidashi",
  },
  {
    id: "demo-2026-05-day-4-bout-2",
    bashoId: demoBasho.id,
    day: 4,
    winnerRikishiId: "kirishima",
    loserRikishiId: "takayasu",
    kimarite: "yorikiri",
  },
  {
    id: "demo-2026-05-day-4-bout-3",
    bashoId: demoBasho.id,
    day: 4,
    winnerRikishiId: "hoshoryu",
    loserRikishiId: "tobizaru",
    kimarite: "uwatenage",
  },
  {
    id: "demo-2026-05-day-4-bout-4",
    bashoId: demoBasho.id,
    day: 4,
    winnerRikishiId: "kotozakura",
    loserRikishiId: "wakatakakage",
    kimarite: "yorikiri",
  },
  {
    id: "demo-2026-05-day-5-bout-1",
    bashoId: demoBasho.id,
    day: 5,
    winnerRikishiId: "hoshoryu",
    loserRikishiId: "onosato",
    kimarite: "shitatenage",
  },
  {
    id: "demo-2026-05-day-5-bout-2",
    bashoId: demoBasho.id,
    day: 5,
    winnerRikishiId: "kotozakura",
    loserRikishiId: "kirishima",
    kimarite: "yorikiri",
  },
  {
    id: "demo-2026-05-day-5-bout-3",
    bashoId: demoBasho.id,
    day: 5,
    winnerRikishiId: "takayasu",
    loserRikishiId: "tobizaru",
    kimarite: "oshidashi",
  },
  {
    id: "demo-2026-05-day-5-bout-4",
    bashoId: demoBasho.id,
    day: 5,
    winnerRikishiId: "wakatakakage",
    loserRikishiId: "ura",
    kimarite: "yorikiri",
  },
];
